services:
  ecommerce:
    build: .
    container_name: ecommerce
    ports:
      - "3015:3015"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - multi_net
    volumes:
      - ./public:/usr/app/public
    
networks:
  multi_net:
    external: true
    labels:
      project: "Ecommerce"
